summarize:
  r:
    data_path_x : /scratch/st-fhendija-1/millon/CodeAttack/data/test.jsonl
    data_path_y : /scratch/st-fhendija-1/millon/CodeAttack/data/test.jsonl

codet5:
  summarize:
    r:
      victim_model_ckpt: '/scratch/st-fhendija-1/millon/CodeAttack/models/pytorch_model.bin'
      max_source_length: 256
      max_target_length: 128
      beam_size: 10

